name: kindlespark-ecommerce-workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Updating Ubuntu system and Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: sudo apt update && sudo apt install heroku neofetch

    - name: Checking the info
        run: neofetch
        
    - name: step 1
      run: echo Hello from KindleSpark workflow
      
    - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          branch: HEAD
          useforce: false
          dynamicFiles: false